[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild" 

[functions.live]
  external_node_modules = ["chrome-aws-lambda-patch-node-16"]