[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[functions]
  node_bundler = "esbuild" 

[functions.live]
  external_node_modules = ["chrome-aws-lambda"]