version: 2.1

triggers:
  - schedule:
      cron: "0,5,15,20,30,35,45,50 * * * *"
      filters:
        branches:
          only:
            - main

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.18.2-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0e:0c:5d:32:f5:b2:f8:26:04:de:92:b1:3b:65:e9:08"
      - checkout
      - restore_cache:
          keys:
            - nextjs-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --no-save
      - run:
          name: Process Live Stream
          command: npm run live
      - save_cache:
          key: nextjs-cache-{{ checksum "package-lock.json" }}
          when: on_success
          paths:
            - ./node_modules

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - bad
