name: Live Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: package-lock.json
          node-version: 18

      - name: Install
        run: |
          npm install --no-save
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

      - name: Run live check
        uses: KaneFreeman/puppeteer-headful@v18.20.2
        id: puppeteer
        timeout-minutes: 2
        with:
          args: npm run live

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
